version: '3.8'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_CLAIM=${CLAIM_TOKEN}
      - TZ=${TZ}
      - PUID=1000  # Replace with your user's UID
      - PGID=1000  # Replace with your user's GID
      - ADVERTISE_IP=http://${IP_ADDRESS}
    hostname: ${HOSTNAME}
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ${MEDIA_LOCATION}:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/web"]
      interval: 1m
      timeout: 10s
      retries: 3
